" Enable pathogen for easy package management
execute pathogen#infect()

syntax on
filetype plugin indent on

set number

set background=dark
colorscheme distinguished

set autoindent
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab

" Highlight lines over 80 characters
highlight OverLength ctermbg=darkgrey guibg=#111111
fun! UpdateMatch()
  " Exclude these file types
  if &ft !~ '^\%(text\)$'
    match OverLength /\%80v.*/
  else
    match NONE
  endif
endfun
autocmd BufEnter,WinEnter * call UpdateMatch()

set cursorline

" rolodex style split window zooming
" taken from http://vim.wikia.com/wiki/Window_zooming_convenience
function! ToggleMaxWins()
  if exists('g:windowMax')
    au! maxCurrWin
    wincmd =
    unlet g:windowMax
  else
    augroup maxCurrWin
        " au BufEnter * wincmd _ | wincmd |
        "
        " only max it vertically
        au! WinEnter * wincmd _
    augroup END
    do maxCurrWin WinEnter
    let g:windowMax=1
  endif
endfunction
nnoremap <C-w>o :call ToggleMaxWins()<CR>

" Enable list of buffers in airline
let g:airline#extensions#tabline#enabled = 1

" CWD outside of vim
let g:ctrlp_working_path_mode = 'rw'

let g:airline_theme = 'serene'

" Buffer shortcuts
nnoremap <leader>n :bn<CR>
nnoremap <leader>d :bd<CR>
