" Enable pathogen for easy package management
execute pathogen#infect()

syntax on
filetype plugin indent on

set number

set background=dark
colorscheme distinguished

set autoindent
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab

" Highlight lines over 80 characters
highlight OverLength ctermbg=darkgrey guibg=#111111
fun! UpdateMatch()
  " Exclude these file types
  if &ft !~ '^\%(text\)$'
    match OverLength /\%80v.*/
  else
    match NONE
  endif
endfun
autocmd BufEnter,WinEnter * call UpdateMatch()

set cursorline

" rolodex style split window zooming
" taken from http://vim.wikia.com/wiki/Window_zooming_convenience
function! ToggleMaxWins()
  if exists('g:windowMax')
    au! maxCurrWin
    wincmd =
    unlet g:windowMax
  else
    augroup maxCurrWin
        " au BufEnter * wincmd _ | wincmd |
        "
        " only max it vertically
        au! WinEnter * wincmd _
    augroup END
    do maxCurrWin WinEnter
    let g:windowMax=1
  endif
endfunction
nnoremap <C-w>o :call ToggleMaxWins()<CR>

" Change leader to spacebar
let mapleader = "\<space>"

" Buffer shortcuts
nnoremap <leader>n :bn<CR>
nnoremap <leader>d :bd<CR>

let g:airline_theme = 'serene'
" Enable list of buffers
let g:airline#extensions#tabline#enabled = 1
" Show tab number
let g:airline#extensions#tabline#buffer_idx_mode = 1
nmap <leader>1 <Plug>AirlineSelectTab1
nmap <leader>2 <Plug>AirlineSelectTab2
nmap <leader>3 <Plug>AirlineSelectTab3
nmap <leader>4 <Plug>AirlineSelectTab4
nmap <leader>5 <Plug>AirlineSelectTab5
nmap <leader>6 <Plug>AirlineSelectTab6
nmap <leader>7 <Plug>AirlineSelectTab7
nmap <leader>8 <Plug>AirlineSelectTab8
nmap <leader>9 <Plug>AirlineSelectTab9
" Show just the filename
"let g:airline#extensions#tabline#fnamemod = ':t'

" CWD outside of vim
let g:ctrlp_working_path_mode = 'rw'
