" Enable pathogen for easy package management
execute pathogen#infect()

syntax on
" Limit syntax columns for performance
set synmaxcol=120
filetype plugin indent on

set background=dark
colorscheme distinguished

set autoindent
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab
set number
" case insensitive search unless capital letter or \C
set smartcase
set colorcolumn=91

inoremap jj <Esc>

" space, file name, right side, line number, space
set statusline=%f%=%l
hi StatusLine ctermfg=59 ctermbg=black

" Light grey (match comment colors)
highlight LineNr ctermfg=59 ctermbg=black

augroup filetypedetect
au BufNewFile,BufRead *.txt setf txt
augroup END

" Change leader to spacebar
let mapleader = "\<space>"

" Buffer shortcuts
nnoremap <leader>n :bn<CR>
nnoremap <leader>p :bp<CR>
nnoremap <leader>d :bd<CR>
nnoremap gn :bn<cr>
nnoremap gp :bp<cr>
nnoremap gd :bd<cr>
nnoremap gl :ls<CR>

" Goyo and Limelight
let g:goyo_width=90
nnoremap <leader><leader> :Goyo<CR>
nnoremap <leader>w :Goyo<CR>:Limelight<CR>

nnoremap <leader>n :set nu!<CR>

" Unite file searching
if executable('ag')
  let g:unite_source_grep_command = 'ag'
  let g:unite_source_grep_default_opts = '-i --vimgrep --hidden --ignore .git'
  let g:unite_source_grep_recursive_opt=''
  let g:unite_source_rec_async_command = ['ag', '--follow', '--nocolor',
    \ '--nogroup', '--hidden', '-g', '']
endif
nmap <C-p> :Unite file_rec/async<cr>
nmap <space>/ :Unite -auto-resize -start-insert -buffer-name=ag  grep:.<cr>
